import unittest
import sys
import os
from pathlib import Path

# Add 'src' directory to module search path to allow relative imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))

from preprocess.handlers.ergoespirometria import ProcessorErgoespirometria
from models.ergoespirometria import InformeErgoespirometria

class TestProcessorErgoespirometria(unittest.TestCase):
    def test_cleaning_and_section_extraction(self):
        # Sample text representing an ergoespirometria report with personal data
        sample_text = """ERGOESPIROMETRÍA : INFORME CLÍNICO
Nombre: PÉREZ GARCÍA, JUAN
NHC: 123456   Edad: 54   Sexo: M
Fecha: 25/05/2026
Procedencia: Cardiología

Paciente bajo tratamiento con beta-bloqueantes.
Realizada en tapiz rodante con protocolo incremental en rampa SOFT.
Realiza 5,32 minutos de ejercicio, alcanzando 3,1 Km/h a carga máxima y 7% de inclinación, limitándose la
prueba por disnea.
Clínica y eléctricamente negativa a la carga de esfuerzo realizada.
Sin inducción de arritmias con el esfuerzo.
FC basal: 70 lpm, VT1: lpm, pico 98 lpm ( 62% del predicho),
Tasa de intercambio respiratorio:
RER basal: 0,78 RER pico: 1,03 RER 1,13 a dos minutos de la recuperación:
Indicando esfuerzo máximo aceptable
Consideramos la prueba VALORABLE Y SUBMÁXIMA.

VALORACIÓN CAPACIDAD FUNCIONAL:
El paciente muestra una capacidad funcional moderada con respuesta normal.

VALORACIÓN RESPUESTA CARDIOVASCULAR:
Respuesta cardiovascular sin hallazgos patológicos significativos.

VALORACIÓN RESPIRATORIA:
Ventilación adecuada sin broncoespasmo inducido por el esfuerzo.

RELACIÓN VENTILACIÓN/PERFUSIÓN:
Adecuada oxigenación y relación V/Q normal.

VALORACIÓN MUSCULATURA PERIFÉRICA:
Sin signos de fatiga periférica prematura.

Conclusiones:
Prueba de esfuerzo submáxima negativa para isquemia miocárdica.

Fdo: Dr. Martínez Colegiado: 232323
"""

        # Create processor with dummy path
        dummy_path = "dummy_ergoespirometria.pdf"
        processor = ProcessorErgoespirometria(dummy_path)
        
        # Inject the sample text
        processor.text = sample_text
        
        # Run clean and extraction
        processor._clean()
        sections = processor._extract_sections()
        
        # Verify section contents
        self.assertIn("inicio", sections)
        self.assertIn("VALORACIÓN CAPACIDAD FUNCIONAL", sections)
        
        # Check that Inicio does NOT contain personal data
        inicio_text = sections["inicio"]
        self.assertNotIn("PÉREZ GARCÍA", inicio_text)
        self.assertNotIn("NHC:", inicio_text)
        self.assertNotIn("Procedencia:", inicio_text)
        
        # Check that Inicio starts with patient clinical content
        self.assertTrue(inicio_text.startswith("Paciente bajo tratamiento con beta-bloqueantes."))
        self.assertTrue(inicio_text.endswith("Consideramos la prueba VALORABLE Y SUBMÁXIMA."))
        
        # Check class properties are set correctly
        self.assertEqual(processor.inicio, inicio_text)
        self.assertEqual(processor.capacidad_funcional, "VALORACIÓN CAPACIDAD FUNCIONAL:\nEl paciente muestra una capacidad funcional moderada con respuesta normal.")
        self.assertEqual(processor.conclusiones, "Conclusiones:\nPrueba de esfuerzo submáxima negativa para isquemia miocárdica.")
        
        # Verify model compatibility
        model = InformeErgoespirometria(
            texto_anonimizado="dummy_anon",
            inicio=processor.inicio,
            capacidad_funcional=processor.capacidad_funcional,
            conclusiones=processor.conclusiones
        )
        self.assertEqual(model.inicio, processor.inicio)
        
        # Clean up output files generated by tests if any
        output_dir = Path("dummy_ergoespirometria_secciones")
        if output_dir.exists():
            for f in output_dir.iterdir():
                f.unlink()
            output_dir.rmdir()
            
        print("Test passed successfully!")

if __name__ == "__main__":
    unittest.main()
